author:
  name: Dasein
  role: Philosopher
  bio:  Known for contributions to phenomenology, hermeneutics, and existentialism.
  location: Munich, Germany

social:
  - id: "x"
    label: "X"
    href: "#_"
  - id: "github"
    label: "GitHub"
    href: "https://github.com/roicort"
  - id: "linkedin"
    label: "Linkedin"
    href: "#_"
  - id: "email"
    label: "Email"
    href: "mailto:"